controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: ready